# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d81161df4a08fee5f45a342a39321acb77e6c6a0e380ac8202ef621a3bf0ed199fe52f7bc1984b37fa28c6286bdd43ef35a8614e32153c1bf724e19aa12d28f5

test:
  secret_key_base: 7b3a1cdf32775526be5449338896491a3482a6e473b97707a512ade97d44161195a2040660f8888f41aeead05b1842d628f2550f88c793bea9f7fb01d3d08133

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
